name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - Source/Cosmodrome/Cosmodrome.csproj
          - Source/Gagarin/Gagarin.csproj
          - Source/Proton/Proton.csproj
          - Source/Soyuz/Soyuz.csproj
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ${{ matrix.project }}
      - name: Build
        run: dotnet build ${{ matrix.project }} --configuration Release --no-restore
